// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';

export function Close():Promise<void>;

export function CloseSerial():Promise<void>;

export function ConnectSerial(arg1:backup.SerialConfig):Promise<void>;

export function ConnectTCP(arg1:backup.TCPConfig):Promise<void>;

export function ConnectUDP(arg1:backup.UDPConfig):Promise<void>;

export function GetSerialPorts():Promise<Array<backup.SerialPortInfo>>;

export function SendData(arg1:string,arg2:Array<number>):Promise<void>;

export function WriteSerial(arg1:Array<number>):Promise<void>;
