// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['backup']['Client']['Close']();
}

export function CloseSerial() {
  return window['go']['backup']['Client']['CloseSerial']();
}

export function ConnectSerial(arg1) {
  return window['go']['backup']['Client']['ConnectSerial'](arg1);
}

export function ConnectTCP(arg1) {
  return window['go']['backup']['Client']['ConnectTCP'](arg1);
}

export function ConnectUDP(arg1) {
  return window['go']['backup']['Client']['ConnectUDP'](arg1);
}

export function GetSerialPorts() {
  return window['go']['backup']['Client']['GetSerialPorts']();
}

export function SendData(arg1, arg2) {
  return window['go']['backup']['Client']['SendData'](arg1, arg2);
}

export function WriteSerial(arg1) {
  return window['go']['backup']['Client']['WriteSerial'](arg1);
}
